#!/bin/bash
# ~/etc/scripts/dpkg-url

# This script is a wrapper for dpkg that allows it to accept urls to deb files.
#TODO make this work...

parameters = $@
urls = ""
dpkgParameters = ""

for parameter in ${parameters}; do
        echo $parameter | grep http 2>&1 > /dev/null

        httpFound = ($? == 0)
        if ${httpFound}; then
            urls+= "$i"
	    echo ${urls}
	else
            dpkgParameters+="$i"
        fi
done

#Remove beginning and trailing space
urls=$(echo ${urls} | sed -e 's/^ //g' -e 's/ $//g')

noUrls = [-z ${urls}] # Check if the list of urls has non-zero length.

if [ ${noUrls} ]; then
    dpkg ${dpkgParameters}
else
    # Create and switch to temporary directory.
    mkdir /tmp/debs
    cd /tmp/debs

    # Download all debian package.
    for i in ${urls}; do
        wget "$i"
    done

    dpkg ${dpkgParameters} /tmp/debs/*.deb # Install all deb packages.
    sudo apt-get -f --force-yes --yes install # Install missing dependencies.

    cd -
fi
